// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Home documents */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homePage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homePage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homePage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homePage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *Home → Slice Zone*
 *
 */
type HomePageDocumentDataSlicesSlice = never;
/**
 * Home document from Prismic
 *
 * - **API ID**: `homePage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "homePage",
    Lang
  >;
/** Content for MainMenu documents */
interface MainMenuDocumentData {
  /**
   * Logo field in *MainMenu*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mainMenu.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  logo: prismic.ImageField<never>;
  /**
   * Links field in *MainMenu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mainMenu.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  links: prismic.GroupField<Simplify<MainMenuDocumentDataLinksItem>>;
  /**
   * Background Color field in *MainMenu*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: mainMenu.backgroundColor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/color
   *
   */
  backgroundColor: prismic.ColorField;
}
/**
 * Item in MainMenu → Links
 *
 */
export interface MainMenuDocumentDataLinksItem {
  /**
   * Label field in *MainMenu → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mainMenu.links[].label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  label: prismic.KeyTextField;
  /**
   * link field in *MainMenu → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: mainMenu.links[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
}
/**
 * MainMenu document from Prismic
 *
 * - **API ID**: `mainMenu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MainMenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MainMenuDocumentData>,
    "mainMenu",
    Lang
  >;
export type AllDocumentTypes = HomePageDocument | MainMenuDocument;
/**
 * Primary content in LandingSection → Primary
 *
 */
interface LandingSectionSliceDefaultPrimary {
  /**
   * Title field in *LandingSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: This is the bigger title
   * - **API ID Path**: landing_section.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.RichTextField;
  /**
   * Subtitle field in *LandingSection → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is the smaller title
   * - **API ID Path**: landing_section.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  subtitle: prismic.TitleField;
  /**
   * Background Image field in *LandingSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_section.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  backgroundImage: prismic.ImageField<never>;
}
/**
 * Default variation for LandingSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LandingSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LandingSectionSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *LandingSection*
 *
 */
type LandingSectionSliceVariation = LandingSectionSliceDefault;
/**
 * LandingSection Shared Slice
 *
 * - **API ID**: `landing_section`
 * - **Description**: `LandingSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LandingSectionSlice = prismic.SharedSlice<
  "landing_section",
  LandingSectionSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      HomePageDocument,
      MainMenuDocumentData,
      MainMenuDocumentDataLinksItem,
      MainMenuDocument,
      AllDocumentTypes,
      LandingSectionSliceDefaultPrimary,
      LandingSectionSliceDefault,
      LandingSectionSliceVariation,
      LandingSectionSlice,
    };
  }
}
